### PR TITLE
[API-1418] Cleanup unit tests

### PR DESCRIPTION
**Pull request by wluu**
- The `specs` folder should be renamed to `test`, since this folder contains the unit tests for `arrow-orm` and will be consistent with our other node_modules like:
  - https://github.com/appcelerator/arrow-admin/tree/master/test
  - https://github.com/appcelerator/arrow/tree/master/test
  - https://github.com/appcelerator/appc.mongo/tree/master/test
- Update to latest `grunt` node_module and other `grunt` components that depends on the latest grunt module.
- Update `should` module to latest version.
- Make the unit test reflect latest `should` functions.

### CODE REVIEW

**Comment by bladedancer** [comment]
@wluu 
Wilson - trying to get everything in for release build today.. This one has a merge conflict and it won't let me resolve it. Can you update the PR pls.

thanks,
gavin

**Comment by wluu** [comment]
@bladedancer, on it. Also, do you want me to bump up the patch version?

**Comment by wluu** [comment]
@bladedancer, Seems like github doesn't like me merging this part: https://github.com/appcelerator/arrow-orm/blob/master/specs/model/core.js#L1372-L1377

If it's all right with you, I want to change that block of code on master to:
```
should(ExtendedUser).be.an.Object();
should(ExtendedUser.connector).be.an.Object();
should(ExtendedUser.connector).be.equal(Connector);
should(ExtendedUser.fields.name).not.be.ok();
should(ExtendedUser.fields.age).be.ok();
should(ExtendedUser.fields.age._own).be.true();
```
And see if it resolves my conflict.

**Comment by wluu** [comment]
@bladedancer, Done, fixed merge conflicts.

**Pull request merged**
